return {
    "neovim/nvim-lspconfig",
    config = function()
        local lspconfig = require("lspconfig")
        lspconfig.angularls.setup({})
        -- lspconfig.ansiblels.setup({})
        -- lspconfig.antlersls.setup({})
        -- lspconfig.apex_ls.setup({})
        -- lspconfig.arduino_language_server.setup({})
        -- lspconfig.asm_lsp.setup({})
        -- lspconfig.ast_grep.setup({})
        -- lspconfig.astro.setup({})
        -- lspconfig.autotools_ls.setup({})
        -- lspconfig.awk_ls.setup({})
        -- lspconfig.azure_pipelines_ls.setup({})
        -- lspconfig.basedpyright.setup({})
        -- lspconfig.bashls.setup({})
        -- lspconfig.beancount.setup({})
        -- lspconfig.bicep.setup({})
        -- lspconfig.biome.setup({})
        -- lspconfig.bright_script.setup({})
        -- lspconfig.bsl_ls.setup({})
        -- lspconfig.buf_ls.setup({})
        -- lspconfig.bzl.setup({})
        -- lspconfig.cairo_ls.setup({})
        -- lspconfig.clangd.setup({})
        -- lspconfig.clarity_lsp.setup({})
        -- lspconfig.clojure_lsp.setup({})
        -- lspconfig.cmake.setup({})
        -- lspconfig.cobol_ls.setup({})
        -- lspconfig.codeqlls.setup({})
        -- lspconfig.coq_lsp.setup({})
        -- lspconfig.crystalline.setup({})
        -- lspconfig.csharp_ls.setup({})
        lspconfig.css_variables.setup({})
        lspconfig.cssls.setup({})
        lspconfig.cssmodules_ls.setup({})
        -- lspconfig.cucumber_language_server.setup({})
        -- lspconfig.custom_elements_ls.setup({})
        -- lspconfig.cypher_ls.setup({})
        -- lspconfig.dagger.setup({})
        -- lspconfig.denols.setup({})
        -- lspconfig.dhall_lsp_server.setup({})
        -- lspconfig.diagnosticls.setup({})
        lspconfig.docker_compose_language_service.setup({})
        lspconfig.dockerls.setup({})
        -- lspconfig.dotls.setup({})
        -- lspconfig.dprint.setup({})
        -- lspconfig.drools_lsp.setup({})
        -- lspconfig.earthlyls.setup({})
        -- lspconfig.efm.setup({})
        -- lspconfig.elixirls.setup({})
        -- lspconfig.elmls.setup({})
        -- lspconfig.elp.setup({})
        -- lspconfig.ember.setup({})
        -- lspconfig.emmet_language_server.setup({})
        -- lspconfig.emmet_ls.setup({})
        -- lspconfig.erg_language_server.setup({})
        -- lspconfig.erlangls.setup({})
        -- lspconfig.esbonio.setup({})
        -- lspconfig.eslint.setup({})
        -- lspconfig.facility_language_server.setup({})
        -- lspconfig.fennel_language_server.setup({})
        -- lspconfig.fennel_ls.setup({})
        -- lspconfig.flux_lsp.setup({})
        -- lspconfig.foam_ls.setup({})
        -- lspconfig.fortls.setup({})
        -- lspconfig.fsautocomplete.setup({})
        -- lspconfig.ginko_ls.setup({})
        -- lspconfig.gitlab_ci_ls.setup({})
        -- lspconfig.glint.setup({})
        -- lspconfig.glsl_analyzer.setup({})
        -- lspconfig.glslls.setup({})
        lspconfig.golangci_lint_ls.setup({})
        lspconfig.gopls.setup({})
        -- lspconfig.gradle_ls.setup({})
        -- lspconfig.grammarly.setup({})
        -- lspconfig.graphql.setup({})
        -- lspconfig.groovyls.setup({})
        -- lspconfig.harper_ls.setup({})
        -- lspconfig.haxe_language_server.setup({})
        -- lspconfig.hdl_checker.setup({})
        -- lspconfig.helm_ls.setup({})
        -- lspconfig.hls.setup({})
        -- lspconfig.hoon_ls.setup({})
        lspconfig.html.setup({})
        -- lspconfig.htmx.setup({})
        -- lspconfig.hydra_lsp.setup({})
        -- lspconfig.hyprls.setup({})
        -- lspconfig.intelephense.setup({})
        --lspconfig.java_language_server.setup({})
        -- lspconfig.jdtls.setup({})
        -- lspconfig.jedi_language_server.setup({})
        -- lspconfig.jinja_lsp.setup({})
        -- lspconfig.jqls.setup({})
        lspconfig.jsonls.setup({})
        lspconfig.jsonnet_ls.setup({})
        -- lspconfig.julials.setup({})
        -- lspconfig.kcl.setup({})
        -- lspconfig.kotlin_language_server.setup({})
        -- lspconfig.lelwel_ls.setup({})
        -- lspconfig.lemminx.setup({})
        -- lspconfig.lexical.setup({})
        -- lspconfig.ltex.setup({})
        lspconfig.lua_ls.setup({})
        lspconfig.luau_lsp.setup({})
        -- lspconfig.lwc_ls.setup({})
        -- lspconfig.markdown_oxide.setup({})
        -- lspconfig.marksman.setup({})
        -- lspconfig.matlab_ls.setup({})
        -- lspconfig.mdx_analyzer.setup({})
        -- lspconfig.mesonlsp.setup({})
        -- lspconfig.millet.setup({})
        -- lspconfig.mm0_ls.setup({})
        -- lspconfig.motoko_lsp.setup({})
        -- lspconfig.move_analyzer.setup({})
        -- lspconfig.mutt_ls.setup({})
        -- lspconfig.neocmake.setup({})
        -- lspconfig.nextls.setup({})
        -- lspconfig.nginx_language_server.setup({})
        -- lspconfig.nickel_ls.setup({})
        -- lspconfig.nil_ls.setup({})
        -- lspconfig.nim_langserver.setup({})
        -- lspconfig.nimls.setup({})
        -- lspconfig.ocamllsp.setup({})
        -- lspconfig.ols.setup({})
        -- lspconfig.omnisharp.setup({})
        -- lspconfig.omnisharp_mono.setup({})
        -- lspconfig.opencl_ls.setup({})
        -- lspconfig.openscad_lsp.setup({})
        -- lspconfig.pbls.setup({})
        -- lspconfig.perlnavigator.setup({})
        -- lspconfig.pest_ls.setup({})
        lspconfig.phpactor.setup({})
        -- lspconfig.pico8_ls.setup({})
        -- lspconfig.pkgbuild_language_server.setup({})
        -- lspconfig.powershell_es.setup({})
        -- lspconfig.prismals.setup({})
        -- lspconfig.prosemd_lsp.setup({})
        -- lspconfig.psalm.setup({})
        -- lspconfig.puppet.setup({})
        -- lspconfig.purescriptls.setup({})
        -- lspconfig.pylsp.setup({})
        lspconfig.pylyzer.setup({})
        lspconfig.pyre.setup({})
        lspconfig.pyright.setup({})
        -- lspconfig.quick_lint_js.setup({})
        -- lspconfig.r_language_server.setup({})
        -- lspconfig.raku_navigator.setup({})
        -- lspconfig.reason_ls.setup({})
        -- lspconfig.regal.setup({})
        -- lspconfig.regols.setup({})
        -- lspconfig.remark_ls.setup({})
        -- lspconfig.rescriptls.setup({})
        -- lspconfig.rnix.setup({})
        -- lspconfig.robotframework_ls.setup({})
        -- lspconfig.rome.setup({})
        -- lspconfig.rubocop.setup({})
        -- lspconfig.ruby_lsp.setup({})
        -- lspconfig.ruff.setup({})
        -- lspconfig.rust_analyzer.setup({})
        -- lspconfig.salt_ls.setup({})
        -- lspconfig.serve_d.setup({})
        -- lspconfig.shopify_theme_ls.setup({})
        -- lspconfig.slint_lsp.setup({})
        -- lspconfig.smithy_ls.setup({})
        -- lspconfig.snakeskin_ls.setup({})
        -- lspconfig.snyk_ls.setup({})
        -- lspconfig.solang.setup({})
        -- lspconfig.solargraph.setup({})
        -- lspconfig.solc.setup({})
        -- lspconfig.solidity.setup({})
        -- lspconfig.solidity_ls.setup({})
        -- lspconfig.solidity_ls_nomicfoundation.setup({})
        -- lspconfig.somesass_ls.setup({})
        -- lspconfig.sorbet.setup({})
        -- lspconfig.sourcery.setup({})
        -- lspconfig.spectral.setup({})
        -- lspconfig.sqlls.setup({})
        -- lspconfig.sqls.setup({})
        -- lspconfig.standardrb.setup({})
        -- lspconfig.starlark_rust.setup({})
        -- lspconfig.starpls.setup({})
        -- lspconfig.steep.setup({})
        -- lspconfig.stimulus_ls.setup({})
        -- lspconfig.stylelint_lsp.setup({})
        -- lspconfig.svelte.setup({})
        -- lspconfig.svlangserver.setup({})
        -- lspconfig.svls.setup({})
        -- lspconfig.swift_mesonls.setup({})
        -- lspconfig.tailwindcss.setup({})
        -- lspconfig.taplo.setup({})
        -- lspconfig.teal_ls.setup({})
        -- lspconfig.templ.setup({})
        -- lspconfig.terraformls.setup({})
        -- lspconfig.texlab.setup({})
        -- lspconfig.textlsp.setup({})
        -- lspconfig.tflint.setup({})
        -- lspconfig.theme_check.setup({})
        -- lspconfig.thriftls.setup({})
        -- lspconfig.tinymist.setup({})
        lspconfig.ts_ls.setup({})
        -- lspconfig.tsp_server.setup({})
        -- lspconfig.twiggy_language_server.setup({})
        -- lspconfig.typos_lsp.setup({})
        -- lspconfig.unocss.setup({})
        -- lspconfig.v_analyzer.setup({})
        -- lspconfig.vacuum.setup({})
        -- lspconfig.vala_ls.setup({})
        -- lspconfig.vale_ls.setup({})
        -- lspconfig.verible.setup({})
        -- lspconfig.veryl_ls.setup({})
        -- lspconfig.vhdl_ls.setup({})
        -- lspconfig.vimls.setup({})
        -- lspconfig.visualforce_ls.setup({})
        -- lspconfig.vls.setup({})
        -- lspconfig.volar.setup({})
        -- lspconfig.vtsls.setup({})
        -- lspconfig.vuels.setup({})
        -- lspconfig.wgsl_analyzer.setup({})
        -- lspconfig.yamlls.setup({})
        -- lspconfig.zk.setup({})
        -- lspconfig.zls.setup({})
    end
}