return {
    "williamboman/mason-lspconfig.nvim",
    config = function()
        require("mason-lspconfig").setup({
            ensure_installed = {
                "angularls",
                --"ansiblels",
               -- "antlersls",
               -- "apex_ls",
               -- "arduino_language_server",
               -- "asm_lsp",
               -- "ast_grep",
               -- "astro",
               -- "autotools_ls",
               -- "awk_ls",
               -- "azure_pipelines_ls",
               -- "basedpyright",
               -- "bashls",
               -- "beancount",
               -- "bicep",
               -- "biome",
               -- "bright_script",
               -- "bsl_ls",
               -- "buf_ls",
               -- "bzl",
               -- "cairo_ls",
               -- "clangd",
                --"clarity_lsp",
                --"clojure_lsp",
                --"cmake",
                --"cobol_ls",
                --"codeqlls",
                --"coq_lsp",
                --"crystalline",
                --"csharp_ls",
                "css_variables",
                "cssls",
                "cssmodules_ls",
                --"cucumber_language_server",
                --"custom_elements_ls",
                --"cypher_ls",
                --"dagger",
                --"denols",
                --"dhall_lsp_server",
                --"diagnosticls",
                "docker_compose_language_service",
                "dockerls",
                --"dotls",
                --"dprint",
                --"drools_lsp",
                --"earthlyls",
                --"efm",
                --"elixirls",
                --"elmls",
                --"elp",
                --"ember",
                --"emmet_language_server",
                --"emmet_ls",
                --"erg_language_server",
                --"erlangls",
                --"esbonio",
                --"eslint",
                --"facility_language_server",
                --"fennel_language_server",
                --"fennel_ls",
                --"flux_lsp",
                --"foam_ls",
                --"fortls",
                --"fsautocomplete",
                --"ginko_ls",
                --"gitlab_ci_ls",
                --"glint",
                --"glsl_analyzer",
                --"glslls",
                "golangci_lint_ls",
                "gopls",
                --"gradle_ls",
                --"grammarly",
                --"graphql",
                --"groovyls",
                --"harper_ls",
                --"haxe_language_server",
                --"hdl_checker",
                --"helm_ls",
                --"hls",
                --"hoon_ls",
                "html",
                --"htmx",
                --"hydra_lsp",
                --"hyprls",
                --"intelephense",
                --"java_language_server",
                --"jdtls",
                --"jedi_language_server",
                --"jinja_lsp",
                --"jqls",
                "jsonls",
                "jsonnet_ls",
                --"julials",
                --"kcl",
                --"kotlin_language_server",
                --"lelwel_ls",
                --"lemminx",
                --"lexical",
                --"ltex",
                "lua_ls",
                "luau_lsp",
                --"lwc_ls",
                --"markdown_oxide",
                --"marksman",
                --"matlab_ls",
                --"mdx_analyzer",
                --"mesonlsp",
                --"millet",
                --"mm0_ls",
                --"motoko_lsp",
                --"move_analyzer",
                --"mutt_ls",
                --"neocmake",
                --"nextls",
                --"nginx_language_server",
                --"nickel_ls",
                --"nil_ls",
                --"nim_langserver",
                --"nimls",
                --"ocamllsp",
                --"ols",
                --"omnisharp",
                --"opencl_ls",
                --"openscad_lsp",
                --"pbls",
                --"perlnavigator",
                --"pest_ls",
                "phpactor",
                --"pico8_ls",
                --"pkgbuild_language_server",
                --"powershell_es",
                --"prismals",
                --"prosemd_lsp",
                --"psalm",
                --"puppet",
                --"purescriptls",
                --"pylsp",
                "pylyzer",
                "pyre",
                "pyright",
                --"quick_lint_js",
                --"r_language_server",
                --"raku_navigator",
                --"reason_ls",
                --"regal",
                --"regols",
                --"remark_ls",
                --"rescriptls",
                --"rnix",
                --"robotframework_ls",
                --"rome",
                --"rubocop",
                --"ruby_lsp",
                --"ruff",
                --"rust_analyzer",
                --"salt_ls",
                --"serve_d",
                --"shopify_theme_ls",
                --"slint_lsp",
                --"smithy_ls",
                --"snakeskin_ls",
                --"snyk_ls",
                --"solang",
                --"solargraph",
                --"solc",
                --"solidity",
                --"solidity_ls",
                --"solidity_ls_nomicfoundation",
                --"somesass_ls",
                --"sorbet",
                --"sourcery",
                --"spectral",
                --"sqlls",
                --"sqls",
                --"standardrb",
                --"starlark_rust",
                --"starpls",
                --"steep",
                --"stimulus_ls",
                --"stylelint_lsp",
                --"svelte",
                --"svlangserver",
                --"svls",
                --"swift_mesonls",
                --"tailwindcss",
                --"taplo",
                --"teal_ls",
                --"templ",
                --"terraformls",
                --"texlab",
                --"textlsp",
                --"tflint",
                --"theme_check",
                --"thriftls",
                --"tinymist",
                "ts_ls",
                --"tsp_server",
                --"twiggy_language_server",
                --"typos_lsp",
                --"unocss",
                --"v_analyzer",
                --"vacuum",
                --"vala_ls",
                --"vale_ls",
                --"verible",
                --"veryl_ls",
                --"vhdl_ls",
                --"vimls",
                --"visualforce_ls",
                --"vls",
                --"volar",
                --"vtsls",
                --"vuels",
                --"wgsl_analyzer",
                --"yamlls",
                --"zk",
                --"zls"
            }
        })
    end
}